trigger:
- master

pool:
  name: Test

# This pipeline has only one job with multiple steps.
# Steps are executed sequentially, which means no parallelism is used.
steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m' # Options for Maven. Make sure no parallel options are set here.
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package' # Maven goal. Again, ensure no parallel execution is configured in Maven itself.
